### ISSUE TITLE
GBAN

### ISSUE THREAD

**Issue by cavoidarlic** [ntkhang03/Goat-Bot#12]
Anh ơi cho em hỏi là  "GBAN « Đã xảy ra lỗi trong quá trình kiểm tra GBAN" thì xử lí như thế nào vậy anh? 🤔
![image](https://user-images.githubusercontent.com/79347941/182561087-9af3166f-8a95-47c8-ab24-66dd2d369389.png)

**Comment by ntkhang03** [comment]
B update lên phiên bản mới nhất nhe. Gõ vào cmd
node update
